name: Stage CI

on:
  push:
    branches: [ stage ]
  pull_request:
    branches: [ stage ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - name: Some actions on Stage 
      run: echo Stage actions complete